module :
  hugoVersion :
    extended : true
    min :      "0.87.0"

params :
  mainSections :
    - post
  featuredImageField : image
  rssFullContent :     true
  favicon :            /favicon.ico?v=1.0

  footer :
    since :      2020
    customText : <a target="_blank" rel="noopener" href="http://beian.miit.gov.cn/">æµ™ICPå¤‡2021009729å·-2</a>

  dateFormat :
    published :   Jan 02, 2006
    lastUpdated : Jan 02, 2006 15:04 MST

  sidebar :
    compact :  false
    emoji :    ğŸ‡¨ğŸ‡³
    subtitle : è„†å¼±çš„äººæ‰ä¼šå››å¤„æ¸¸è¯´è‡ªå·±çš„ä¸å¹¸ï¼Œåšå¼ºçš„äººåªä¼šä¸åŠ¨å£°è‰²åœ°æ„ˆæ¸å¼ºå¤§ã€‚è¿™é‡Œæ˜¯ DesnLee çš„å‰ç«¯åšå®¢ï¼Œæ¬¢è¿ä½ çš„æ¥è®¿ï¼
    avatar :
      enabled : true
      local :   false
      src :     https://cdn.desnlee.com/img/blog/avatar.jpg

  article :
    math :        true
    toc :         true
    readingTime : true
    license :
      enabled : true
      default : Licensed under CC BY-NC-SA 4.0

  comments :
    enabled :  false
    provider : disqus

    disqusjs :
      shortname :
      apiUrl :
      apiKey :
      admin :
      adminLabel :

    utterances :
      repo :
      issueTerm : pathname
      label :

        beaudar:
            repo:
            issueTerm: pathname
            label:
            theme:        

        remark42:
            host:
            site:
            locale:

    vssue :
      platform :
      owner :
      repo :
      clientId :
      clientSecret :
      autoCreateIssue : false

    # Waline client configuration see: https://waline.js.org/en/reference/client.html
    waline :
      serverURL :
      lang :
      visitor :
      avatar :
      emoji :
        - https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo
      requiredMeta :
        - name
        - email
        - url
      placeholder :
      locale :
        admin : Admin

    twikoo :
      envId :
      region :
      path :
      lang :

    giscus :
      repo :
      repoID :
      category :
      categoryID :
      mapping :
      strict :
      lightTheme :
      darkTheme :
      reactionsEnabled : 1
      emitMetadata :     0
      inputPosition :
      lang :

    gitalk :
      owner :
      admin :
      repo :
      clientID :
      clientSecret :

    cusdis :
      host :
      id :

  widgets :
    homepage :
      - type : search
      - type : archives
        params :
          limit : 10
      - type : tag-cloud
        params :
          limit : 10
    page :
      - type : toc

  opengraph :
    twitter :
      # Your Twitter username
      site : DesnLee

      # Available values: summary, summary_large_image
      card : summary_large_image

  defaultImage :
    opengraph :
      enabled : true
      local :   false
      src :     https://cdn.desnlee.com/img/blog/opengraph.jpg

  colorScheme :
    # Display toggle
    toggle :  true

    # Available values: auto, light, dark
    default : auto

  imageProcessing :
    cover :
      enabled : true
    content :
      enabled : true

menu :
  main :
    - identifier : home
      name :       Home
      url :        /
      weight :     -100
      params :
        icon : home

    - identifier : categories
      name :       Categories
      url :        /categories
      weight :     -90
      params :
        icon : categories

  social :
    - identifier : github
      name :       Github
      url :        https://github.com/DesnLee
      weight :     -100
      params :
        icon : github

    - identifier : rss
      name :       RSS
      url :        /post/index.xml
      weight :     -100
      params :
        icon : rss
